events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 443 ssl;
        server_name yaepark.42.fr;

        ssl_certificate     /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # TLSv1.2 or TLSv1.3 only, no TLSv1/1.1 or SSLv3.
        ssl_protocols TLSv1.2 TLSv1.3;

        root /var/www/html;
		autoindex on;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # Hand PHP requests to the wordpress container on the docker network.
        location ~ \.php$ {
            try_files $uri $uri/ /index.php?$query_string;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            fastcgi_param HTTPS on; #specify that its working with HTTPS
            # include /etc/nginx/fastcgi.conf;
            # fastcgi_pass wordpress:9000;     # service-name DNS over the network
            # fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}